version: "3.9"
services:
  database:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - ./.docker/volumes/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - order-service-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - order-service-network
    tty: true
    stdin_open: true

networks:
  order-service-network:
    driver: bridge
